version: "3.9"

services:
  interrogate_forever:
    build:
      context: .
      dockerfile: Dockerfile
    image: sesopenko/interrogate_forever:latest
    container_name: interrogate_forever_watch
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - HF_HOME=/app/data/transformers
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
